-- AlterTable
ALTER TABLE "Verb" ADD COLUMN     "exemplo" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "exemploPt" TEXT;

-- AlterTable
ALTER TABLE "Word" ADD COLUMN     "exemploPt" TEXT,
ALTER COLUMN "artigo" DROP NOT NULL,
ALTER COLUMN "artigo" DROP DEFAULT,
ALTER COLUMN "genero" DROP NOT NULL,
ALTER COLUMN "genero" DROP DEFAULT,
ALTER COLUMN "plural" DROP NOT NULL,
ALTER COLUMN "plural" DROP DEFAULT;
